name: Generate gh-page

on:
  push:
    branches:
      - main
jobs:
  generate:
    name: Generate Parser
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - name: Generate parser files
        run: |
          npx tree-sitter generate
          npx tree-sitter build-wasm

      - name: Checkout gh-pages branch to ./gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./gh-pages

      - run: mv *.wasm ./gh-pages

      - name: Commit generated wasm binding to the gh-pages branch
        run: |
          cd ./gh-pages
          git add *.wasm
          git commit -m "Generate WASM binding" || true
          git push
